export const PATHS = {
  MAIN: '/',
  LOGIN: '/login',
  CATALOG: '/app/catalog',
  PRODUCTS: '/app/products',
  VITRINA: '/app/vitrina',
  START: '/app/start',
  MESSAGES: '/app/messages',
  SUBSCRIBERS: '/app/subscribers',
  SHARE: '/app/share',
  ORDERS: '/app/orders',
  SITE: '/site/',
  COMMON: '/app/settings/common',
  DELIVERY: '/app/settings/delivery',
  PAYMENT: '/app/settings/payment',
  PROMOCODES: '/app/settings/promocodes',
  VIEW: '/app/settings/views',
  ACCESS: '/app/settings/access',
  INTEGRATION: '/app/settings/integrations',
  NOTIFICATIONS: '/app/settings/notifications',
  TARIFF: '/app/settings/tariff',
}
