export const QUERY_KEY = {
  getAllShops: 'getAllShops',
  getAllCategories: 'getAllCategories',
  getAllGoods: 'getAllGoods',
  getGoodsById: 'getGoodsById',
  getAllDelivery: 'getAllDelivery',
  getAllPayment: 'getAllPayment',
  getAllPromocode: 'getAllPromocode',
  getAllShare: 'getAllShare',
  getAllSubscribers: 'getAllSubscribers',
  getSubscriberById: 'getSubscriberById',
  getAllOrders: 'getAllOrders',
  getAllUsersMessage: 'getAllUsersMessage',
  getAllMessages: 'getAllMessages',
  getCart: 'getCart',
}
