export const APP_PATH = {
  MAIN: '/',
  LOGIN: '/login',
  START: '/start',
  CATALOG: '/catalog',
  ORDERS: '/orders',
  MESSAGE: '/message',
  SUBSCRIBERS: '/subscribers',
  SHARE: '/share',
  SITE: '/site/:id',
  COMMON: '/settings/common',
  DELIVERY: '/settings/delivery',
  PAYMENT: '/settings/payment',
  PROMOCODES: '/settings/promocodes',
  VIEW: '/settings/view',
  ACCESS: '/settings/access',
  INTEGRATION: '/settings/integration',
  NOTIFICATIONS: '/settings/notifications',
  TARIFF: '/settings/tariff',
}
