export const APP_PATH = {
  MAIN: '/',
  LOGIN: '/login',
  START: '/start',
  CATALOG: '/catalog/:id',
  ORDERS: '/orders/:id',
  MESSAGE: '/message/:id',
  SUBSCRIBERS: '/subscribers/:id',
  SHARE: '/share/:id',
  SITE: '/site/:id',
  COMMON: '/settings/common/:id',
  DELIVERY: '/settings/delivery/:id',
  PAYMENT: '/settings/payment/:id',
  PROMOCODES: '/settings/promocodes/:id',
  VIEW: '/settings/view/:id',
  ACCESS: '/settings/access/:id',
  INTEGRATION: '/settings/integration/:id',
  NOTIFICATIONS: '/settings/notifications/:id',
  TARIFF: '/settings/tariff/:id',
}

export const DYNAMIC_LINK = (id: string) => ({
  CATALOG: `/catalog/${id}`,
  ORDERS: `/orders/${id}`,
  MESSAGE: `/message/${id}`,
  SUBSCRIBERS: `/subscribers/${id}`,
  SHARE: `/share/${id}`,
  SITE: `/site/${id}`,
  COMMON: `/settings/common/${id}`,
  DELIVERY: `/settings/delivery/${id}`,
  PAYMENT: `/settings/payment/${id}`,
  PROMOCODES: `/settings/promocodes/${id}`,
  VIEW: `/settings/view/${id}`,
  ACCESS: `/settings/access/${id}`,
  INTEGRATION: `/settings/integration/${id}`,
  NOTIFICATIONS: `/settings/notifications/${id}`,
  TARIFF: `/settings/tariff/${id}`,
})
